### ISSUE TITLE
get_queue failing and stopping js execution

### ISSUE THREAD

**Issue by sGerli** [dillpixel/fitbit-asap#1] opened 2019-01-15 01:45 UTC
For some reason the method get_queue is sometimes returning 0 instead of an array, @gregoiresage believes it's because of lack of available space on device.
```
App: Unhandled TypeError: Expected a function.
  queue at node_modules/fitbit-asap/app.js:16,5
  enqueue at node_modules/fitbit-asap/app.js:47,5
  asap at node_modules/fitbit-google-analytics/app.js:43,5
  send$1 at node_modules/fitbit-google-analytics/app.js:55,9
```
(Credit to @gregoiresage for helping me debug and find more info about the issue)

Adding a few lines (As suggested by @gregoiresage) seemed to fix this issue for me (at least for the small time I've been testing it) but I don't think it is a good permanent fix:

```js
var get_queue = function () {
    try {
        var queue = readFileSync("_asap_queue", "cbor");
        if (!Array.isArray(queue)) {
            return [];
        }
        return readFileSync("_asap_queue", "cbor");
    }
    catch (error) {
        return [];
    }
};
```

**Comment by daveyjones** [comment] 2019-01-15 15:45
Thanks @sGerli — yes, the issue is probably that the buffer limit is being reached and ASAP isn't checking the buffer limit. I'm marking this as a bug and I'm working on a fix.

**Comment by daveyjones** [comment] 2019-01-20 07:55
@sGerli I've removed ASAP as a dependency from Fitbit Google Analytics, which now uses the new File Transfer Upload API that was introduced in Fitbit OS 3.0.

**Comment by daveyjones** [comment] 2019-01-23 19:37
@sGerli I've been troubleshooting this but so far no luck.

It's doubtful to me that the device is running out of disk space—it's much more likely that the device would run out of memory when reading the queue. However, if the device was running out of memory, then you would get an error like this:
```
App: Fatal Jerryscript Error: ERR_OUT_OF_MEMORY
```
If you're willing to share your code privately, I would love to take a look and see what's going on to cause this issue.

**Comment by daveyjones** [comment] 2019-01-23 19:46
@sGerli My email is david@dillpixel.com if you'd like to send anything over.

**Closed** 2019-01-23 21:13 UTC
Labels: bug

**Comment by daveyjones** [comment] 2019-01-23 21:36
@sGerli I added try/catch blocks around all file operations. This should solve this issue so I went ahead and closed the issue. Feel free to comment if you run into it again and I'll re-open and continue investigating. Thanks!
