### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by Artaud** [dillpixel/fitbit-asap#7] opened 2019-03-01 13:04 UTC
According to [this post](https://community.fitbit.com/t5/SDK-Development/Unit-tests-using-Jest/td-p/2896771), it should be possible to run Jest tests with Fitbit apps.

I would subscribe to some test suite since otherwise we are probably not going to be able to test some more in-depth scenarios (like enqueing multiple messages with simulated intermittent connectivity), at least not in a repeatable way.

**Comment by daveyjones** [comment] 2019-06-27 17:33
I'm going to close this because the issue is too broad. Feel free to open new issues with specific test cases that should be covered.

**Closed by daveyjones** 2019-06-27 17:33 UTC
Labels: enhancement
